Perfect Bansal
L6CG13

In [ ]:
#Python program that converts between different units of measurement.
def convert_units(conversion_type, value, direction):
    """
    Converts units based on the type and direction selected.

    Parameters:
    conversion_type (str): Type of conversion ('length', 'weight', 'volume')
    value (float): The numeric value to convert
    direction (str): Specific conversion direction

    Returns:
    float: Converted value
    """

    if conversion_type == "length":
        if direction == "m_to_ft":
            return value * 3.28084
        elif direction == "ft_to_m":
            return value / 3.28084

    elif conversion_type == "weight":
        if direction == "kg_to_lbs":
            return value * 2.20462
        elif direction == "lbs_to_kg":
            return value / 2.20462

    elif conversion_type == "volume":
        if direction == "l_to_gal":
            return value * 0.264172
        elif direction == "gal_to_l":
            return value / 0.264172

    else:
        return None


def main():
    try:
        print("Select conversion type: length / weight / volume")
        conversion_type = input("Enter type: ").lower()

        value = float(input("Enter value to convert: "))

        print("Enter conversion direction:")
        print("Length: m_to_ft / ft_to_m")
        print("Weight: kg_to_lbs / lbs_to_kg")
        print("Volume: l_to_gal / gal_to_l")

        direction = input("Enter direction: ").lower()

        result = convert_units(conversion_type, value, direction)

        if result is None:
            print("Unsupported conversion type or direction.")
        else:
            print("Converted value:", round(result, 4))

    except ValueError:
        print("Invalid input! Please enter a numeric value.")


if __name__ == "__main__":
    main()

Select conversion type: length / weight / volume
Enter type: length
Enter value to convert: 20
Enter conversion direction:
Length: m_to_ft / ft_to_m
Weight: kg_to_lbs / lbs_to_kg
Volume: l_to_gal / gal_to_l
Enter direction: m_to_ft
Converted value: 65.6168


In [ ]:
#Python program that performs various mathematical operations on a list of numbers.
def find_sum(numbers):
    """
    Returns the sum of a list of numbers.

    Parameters:
    numbers (list): List of numeric values

    Returns:
    float: Sum of numbers
    """
    return sum(numbers)


def find_average(numbers):
    """
    Returns the average of a list of numbers.

    Parameters:
    numbers (list): List of numeric values

    Returns:
    float: Average of numbers
    """
    return sum(numbers) / len(numbers)


def find_maximum(numbers):
    """
    Returns the maximum value in a list.

    Parameters:
    numbers (list): List of numeric values

    Returns:
    float: Maximum value
    """
    return max(numbers)


def find_minimum(numbers):
    """
    Returns the minimum value in a list.

    Parameters:
    numbers (list): List of numeric values

    Returns:
    float: Minimum value
    """
    return min(numbers)


def main():
    try:
        print("Choose operation: sum / average / max / min")
        operation = input("Enter operation: ").lower()

        user_input = input("Enter numbers separated by spaces: ")
        numbers = list(map(float, user_input.split()))

        if not numbers:
            raise ValueError("Empty list is not allowed.")

        if operation == "sum":
            print("Result:", find_sum(numbers))
        elif operation == "average":
            print("Result:", find_average(numbers))
        elif operation == "max":
            print("Result:", find_maximum(numbers))
        elif operation == "min":
            print("Result:", find_minimum(numbers))
        else:
            print("Invalid operation selected.")

    except ValueError:
        print("Invalid input! Please enter valid numbers.")


if __name__ == "__main__":
    main()

Choose operation: sum / average / max / min
Enter operation: sum
Enter numbers separated by spaces: 2 5 7
Result: 14.0


In [ ]:
matrix= [
    [1 , 2 , 3],
    [4 , 5 , 6]
]
print(matrix)

[[1, 2, 3], [4, 5, 6]]


In [4]:
# 4.2 Exercise on List Manipulation
# 1. Extract Every Other Element
def extract_every_other(lst):
    """Returns every other element starting from first."""
    return lst[::2]


# 2. Get Sublist (inclusive)
def get_sublist(lst, start, end):
    """Returns sublist from start to end (inclusive)."""
    return lst[start:end+1]


# 3. Reverse List
def reverse_list(lst):
    """Returns reversed list using slicing."""
    return lst[::-1]


# 4. Remove First and Last
def remove_first_last(lst):
    """Removes first and last elements."""
    return lst[1:-1]


# 5. Get First n Elements
def get_first_n(lst, n):
    """Returns first n elements."""
    return lst[:n]


# 6. Get Last n Elements
def get_last_n(lst, n):
    """Returns last n elements."""
    return lst[-n:]


# 7. Reverse Skip
def reverse_skip(lst):
    """Returns every second element starting from second-last, backwards."""
    return lst[-2::-2]

In [ ]:
import numpy as np

In [5]:
#  4.3 Exercise on Nested List
# 1. Flatten Nested List (Simple)
def flatten(lst):
    """Flattens one level nested list."""
    result = []
    for item in lst:
        for element in item:
            result.append(element)
    return result
# 2. Access Nested Element
def access_nested_element(lst, indices):
    """
    Returns element from nested list using list of indices.
    """
    element = lst
    for index in indices:
        element = element[index]
    return element
# 3. Sum Nested (Any Depth)
def sum_nested(lst):
    """Returns sum of all elements in nested list."""
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total
# 4. Remove Element from Nested List
def remove_element(lst, elem):
    """Removes all occurrences of elem from nested list."""
    new_list = []
    for item in lst:
        if isinstance(item, list):
            new_list.append(remove_element(item, elem))
        elif item != elem:
            new_list.append(item)
    return new_list
# 5. Find Maximum in Nested List
def find_max(lst):
    """Finds maximum element in nested list."""
    max_value = float('-inf')
    for item in lst:
        if isinstance(item, list):
            max_value = max(max_value, find_max(item))
        else:
            max_value = max(max_value, item)
    return max_value
# 6. Count Occurrences in Nested List
def count_occurrences(lst, elem):
    """Counts occurrences of elem in nested list."""
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count
# 7. Deep Flatten (Any Depth)
def deep_flatten(lst):
    """Flattens deeply nested list."""
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result
# 8. Average of Nested List
def average_nested(lst):
    """Returns average of nested list elements."""
    flat_list = deep_flatten(lst)
    return sum(flat_list) / len(flat_list)

In [6]:
import numpy as np


In [7]:
# array creation
# 1. Empty array 2x2
arr1 = np.empty((2,2))
print("Empty 2x2 array:\n", arr1)

# 2. All ones array 4x2
arr2 = np.ones((4,2))
print("\nAll ones 4x2:\n", arr2)

# 3. Array filled with specific value
arr3 = np.full((3,3), 7)
print("\nFull array (3x3 filled with 7):\n", arr3)

# 4. Zeros like existing array
arr4 = np.zeros_like(arr2)
print("\nZeros like arr2:\n", arr4)

# 5. Ones like existing array
arr5 = np.ones_like(arr2)
print("\nOnes like arr2:\n", arr5)

# 6. Convert list to numpy array
new_list = [1,2,3,4]
arr6 = np.array(new_list)
print("\nConverted list to array:\n", arr6)

Empty 2x2 array:
 [[2.20052282e-315 0.00000000e+000]
 [1.97626258e-323             nan]]

All ones 4x2:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Full array (3x3 filled with 7):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros like arr2:
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

Ones like arr2:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Converted list to array:
 [1 2 3 4]


In [8]:
# Array multiplication
# 1. Values from 10 to 49
a = np.arange(10,50)
print("Array 10 to 49:\n", a)

# 2. 3x3 matrix from 0 to 8
b = np.arange(9).reshape(3,3)
print("\n3x3 matrix 0-8:\n", b)

# 3. 3x3 identity matrix
c = np.eye(3)
print("\nIdentity matrix:\n", c)

# 4. Random array size 30 and mean
d = np.random.random(30)
print("\nMean:", d.mean())

# 5. 10x10 random array min & max
e = np.random.random((10,10))
print("\nMinimum:", e.min())
print("Maximum:", e.max())

# 6. Zero array size 10 and replace 5th element
f = np.zeros(10)
f[4] = 1
print("\nReplace 5th element:\n", f)

# 7. Reverse array
arr = np.array([1,2,0,0,4,0])
print("\nReversed:", arr[::-1])

# 8. 2D array with 1 border and 0 inside
g = np.ones((5,5))
g[1:-1,1:-1] = 0
print("\nBorder 1 inside 0:\n", g)

# 9. 8x8 checkerboard
h = np.zeros((8,8))
h[1::2, ::2] = 1
h[::2, 1::2] = 1
print("\nCheckerboard:\n", h)

Array 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 matrix 0-8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Mean: 0.4789426065268983

Minimum: 0.008573153902060149
Maximum: 0.9932402013710077

Replace 5th element:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

Reversed: [0 4 0 0 2 1]

Border 1 inside 0:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

Checkerboard:
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [9]:
# Array Operations
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

# 1. Add
print("Addition:\n", x + y)

# 2. Subtract
print("\nSubtraction:\n", x - y)

# 3. Multiply by integer
print("\nMultiply x by 3:\n", x * 3)

# 4. Square
print("\nSquare of x:\n", x**2)

# 5. Dot products
print("\nDot v and w:", np.dot(v,w))
print("Dot x and v:", np.dot(x,v))
print("Dot x and y:\n", np.dot(x,y))

# 6. Concatenate
print("\nConcatenate x and y (row):\n", np.vstack((x,y)))
print("\nConcatenate v and w (column):\n", np.vstack((v,w)))

# 7. Concatenate x and v
# This will give error because dimensions do not match
# x is 2D (2x2) and v is 1D (2,)
# They must have same dimensions

Addition:
 [[ 6  8]
 [10 13]]

Subtraction:
 [[-4 -4]
 [-4 -3]]

Multiply x by 3:
 [[ 3  6]
 [ 9 15]]

Square of x:
 [[ 1  4]
 [ 9 25]]

Dot v and w: 219
Dot x and v: [29 77]
Dot x and y:
 [[19 22]
 [50 58]]

Concatenate x and y (row):
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v and w (column):
 [[ 9 10]
 [11 12]]


In [10]:
#Matrix operations
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# 1. Prove A * A^-1 = I
A_inv = np.linalg.inv(A)
print("A * A^-1:\n", np.dot(A, A_inv))

# 2. Prove AB != BA
print("\nAB:\n", np.dot(A,B))
print("\nBA:\n", np.dot(B,A))

# 3. Prove (AB)^T = B^T A^T
left = np.dot(A,B).T
right = np.dot(B.T, A.T)
print("\n(AB)^T:\n", left)
print("\nB^T A^T:\n", right)

A * A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB:
 [[23 13]
 [51 29]]

BA:
 [[36 44]
 [13 16]]

(AB)^T:
 [[23 51]
 [13 29]]

B^T A^T:
 [[23 51]
 [13 29]]


In [11]:
# 10.2 Experiment: How Fast is NumPy?
import time

size = 1000000

# Create Python lists
list1 = list(range(size))
list2 = list(range(size))

# Create NumPy arrays
arr1 = np.array(list1)
arr2 = np.array(list2)

# 1. Element-wise Addition
start = time.time()
result = [list1[i] + list2[i] for i in range(size)]
print("Python List Addition Time:", time.time() - start)

start = time.time()
result = arr1 + arr2
print("NumPy Addition Time:", time.time() - start)


# 2. Element-wise Multiplication
start = time.time()
result = [list1[i] * list2[i] for i in range(size)]
print("Python List Multiplication Time:", time.time() - start)

start = time.time()
result = arr1 * arr2
print("NumPy Multiplication Time:", time.time() - start)


# 3. Dot Product
start = time.time()
dot = sum(list1[i] * list2[i] for i in range(size))
print("Python Dot Product Time:", time.time() - start)

start = time.time()
dot = np.dot(arr1, arr2)
print("NumPy Dot Product Time:", time.time() - start)


# 4. Matrix Multiplication (1000x1000)
m1 = np.random.random((1000,1000))
m2 = np.random.random((1000,1000))

start = time.time()
result = np.dot(m1, m2)
print("NumPy Matrix Multiplication Time:", time.time() - start)

Python List Addition Time: 0.06927323341369629
NumPy Addition Time: 0.009098052978515625
Python List Multiplication Time: 0.06711626052856445
NumPy Multiplication Time: 0.009761810302734375
Python Dot Product Time: 0.06824564933776855
NumPy Dot Product Time: 0.0009837150573730469
NumPy Matrix Multiplication Time: 0.054207563400268555
